### ISSUE TITLE
iOS security library docs 

### ISSUE THREAD

**Issue by crafterm** [amitaymolko/react-native-rsa-native#1]
@amitaymolko here's the docs for using iOS inbuilt security libraries:

https://developer.apple.com/library/content/documentation/Security/Conceptual/CertKeyTrustProgGuide/KeyGen.html#//apple_ref/doc/uid/TP40001358-CH212-SW1

whats your thoughts on updating to use the Sec* methods on iOS, and keychain for storage on both iOS and Android?

**Comment by amitaymolko** [comment]
@crafterm SecKey methods on iOS is a very good idea, including openssl is pretty heavy and forces extra libraries.
Keychain would also be a great addition.
Creating 2 new issues so we can track separately

**Comment by crafterm** [comment]
@amitaymolko great mate, i'll close this one off then and we can chat on those other issues then more specifically.
