### ISSUE TITLE
Custom public key

### ISSUE THREAD

**Issue by DzmitrySakalouski** [amitaymolko/react-native-rsa-native#103]
Hello

How can I attach custom public key? I just pasted it into RSA.encrypt - but I've got an error

Thanks.

![image](https://user-images.githubusercontent.com/55082507/102629010-a28e5b80-415b-11eb-8db6-ef93f8e56016.png)

**Comment by khaledwj90** [comment]
It seems you missed to add BEGIN & END
-----BEGIN PUBLIC KEY-----
{YOUR_KEY} 
-----END PUBLIC KEY-----

**Comment by safeer-ahmed** [comment]
As mentioned above, get it done like:

RSA.encrypt(value, '-----BEGIN PUBLIC KEY-----' +
        Keys.RSA_PUBLIC_KEY +
        '-----END PUBLIC KEY-----',
    ).then((encodedMessage) => {
      console.log('the encoded message is ', encodedMessage);
 });

**Comment by Dror-Bar** [comment]
When I try that I get this error: `-----END RSA PUBLIC KEY not found`
Edit: what finally worked for me [here](https://github.com/amitaymolko/react-native-rsa-native/issues/62#issuecomment-1141884771)
