### ISSUE TITLE
Decryption of content on other device/account doesn't work

### ISSUE THREAD

**Issue by chringseng** [amitaymolko/react-native-rsa-native#104]
I'm really on my limit and need help with an error message, which I will get, if I want to decrypt a message on the other device. Do anybody knows what this message means:

`Error: error:04000089:RSA routines:OPENSSL_internal:PKCS_DECODING_ERROR`

I do everything like in this example here (without of keychain):

1. Generating 4096 keys (on both devices and storing puKey in DB)
2. Encrypting the message with the puKey of the other device
3. Decrypting the message on the first or second device with prKey

Keys are all correct formated and the funny thing is, that on the sender device decryption and encryption works.
Only prKey of receiver device makes problems.

Is it my fail or a bug?

**Comment by obie3** [comment]
I'm encountering the same challenge, please were you able to resolve your challenge and how did you do it if yes
