### ISSUE TITLE
Android API 23 raising a "Only RSAKeyGenParameterSpec supported" error

### ISSUE THREAD

**Issue by crafterm** [amitaymolko/react-native-rsa-native#12]
Hi @amitaymolko 

Hope all is going well mate.

Noticed in our testing with the Pixel emulator, API 23, that RSA land is throwing an error when generating keypairs mentioning that only RSAKeyGenParameterSpec is supported:

<img width="213" alt="screen_shot_2017-07-19_at_12 12 31_pm_720" src="https://user-images.githubusercontent.com/397/28351947-b838795e-6c96-11e7-8602-16c1bf96f9e2.png">

With a Nexus 5X simulator (API 24) all good, so looks like only an 23 issue perhaps?

Looking at the generate method that accepts a key tag for keystore identification, the KeyPairGenerator is given a KeyPairGenParameter rather than a RSAKeyGenParameterSpec. I had a bit of look at using RSAKeyGenParameterSpec rather than KeyPairGenParameter/builder, but the former doens't appear to have any keystore integration...

Any thoughts mate what might be going on in API 23 land?

Cheers,

Marcus

**Comment by amitaymolko** [comment]
Hey @crafterm,
I'll look into it when I get the chance

**Comment by crafterm** [comment]
Thanks @amitaymolko - looking forward to hearing from you mate.

**Comment by crafterm** [comment]
Mate, reckon I've fixed it, PR coming!

**Comment by amitaymolko** [comment]
Fixed by @crafterm In PR #13 
Thanks for this
