### ISSUE TITLE
sample code for block encrypt

### ISSUE THREAD

**Issue by bestlbw** [amitaymolko/react-native-rsa-native#17]
beyond the max length will return undefined ，

**Comment by amitaymolko** [comment]
Hey @bestlbw 
Can you please give us some more information?
What code are you running?
Android/iOS?

**Comment by bestlbw** [comment]
@amitaymolko  ios ，i need to encrypt json string that greater than 117，will return ‘undefined’，so i   
try to change the code realize the block cyphers ，would u  give me a example ？ thanks！

**Comment by amitaymolko** [comment]
can you send the code you are running?

**Comment by bestlbw** [comment]
the json String like this ：
{"systemId":"000001","reserve1":"","reserve2":"","transflag":1,"message":{"head"{"answerCode":"000000","trxnDate":1505905415917,"trxnFlag":1,"trxnSeq":0,"trxnCode":1003},"requestBody":{"securityUserId":"bjzxmr","pageStart":1,"numberOfPages":20,"custometype":"I","searchCondition":"I","searchValue":"111","searchType":"01"}}}

**Comment by amitaymolko** [comment]
can you please send the full code that you are running so i can properly recreate the issue on my end?

**Comment by bestlbw** [comment]
oh no ，i think u don,t know my meaning ,  changing the code for solving ‘unknown block type’ error

**Comment by amitaymolko** [comment]
In order for me to recreate your issue I need a copy of the code you are running to get the ‘unknown block type’ error.

I need this to understand the issue better and things like:
What functions are you calling in the library? In what order?

**Comment by bestlbw** [comment]
ok ，i know your meaning， 
const params={"systemId":"000001","reserve1":"","reserve2":"","transflag":1,"requestBody":{"securityUserId":"bjzxmr","pageStart":1,"numberOfPages":20,"custometype":"I","searchCondition":"I","searchValue":"111","searchType":"01"}}}
RSA.encrypt(params, pubKey)

**Comment by amitaymolko** [comment]
`RSA.encrypt` takes a string param to encrypt.

try something like:
`RSA.encrypt(JSON.stringify(params), pubKey)`

**Comment by bestlbw** [comment]
i know , i just omitted， until return ‘undifined’

**Comment by amitaymolko** [comment]
So please send me full code you are running, without omitting anything.
You are making it very difficult to evaluate this issue...

**Comment by bestlbw** [comment]
cry。。。 
 `const params={"systemId":"000001","reserve1":"","reserve2":"","transflag":1,"requestBody":{"securityUserId":"bjzxmr","pageStart":1,"numberOfPages":20,"custometype":"I","searchCondition":"I","searchValue":"111","searchType":"01"}}}
 RSA.encrypt(JSON.stringify(params), pubKey)`  return ‘undifined’

**Comment by amitaymolko** [comment]
ok I rewrote the encrypt decrypt for iOS to handle bigger blocks of data.
Please test with latest version 1.0.10

**Comment by bestlbw** [comment]
@ thank you very much to solve my problem，i try to change the code but no effect，thanks

**Comment by earonesty** [comment]
The problem is that you cannnot encrypt blocks larger then your key with RSA.   Instead, use AES to encrypt the block and use RSA to encrypt the random AES key.

**Comment by earonesty** [comment]
Worse:   it looks like the code on ios is broken if the data has a null byte in it (which it can!).

**Comment by earonesty** [comment]
Do this for large data:

```
key = random(32)
iv = random(16)
encdata=encryptaes(data, key)
enckey = encryptrsa(key)
result = iv+enckey+encdata

```
