### ISSUE TITLE
dyld: Symbol not found: _kSecKeyAlgorithmRSAEncryptionPKCS1

### ISSUE THREAD

**Issue by bestlbw** [amitaymolko/react-native-rsa-native#18]
run simulator is ok ,but run real devices output：
![image](https://user-images.githubusercontent.com/23213008/30793720-54d814c4-a1f6-11e7-936d-822b7d096020.png)

what should i do ？ thanks for any help

**Comment by amitaymolko** [comment]
What device/iOS version are you running?

**Comment by bestlbw** [comment]
@amitaymolko  ios version is  9.3.5

**Comment by amitaymolko** [comment]
seems that this library was introduced in iOS 10.0
https://developer.apple.com/documentation/security/kseckeyalgorithmrsaencryptionpkcs1
