### ISSUE TITLE
Does not work with Android

### ISSUE THREAD

**Issue by NotTooReact89** [amitaymolko/react-native-rsa-native#20]
Hi,

I get an error saying "Keychain error:  TypeError: Cannot read property 'encrypt' of undefined" when I try the code in android. Works fine in iOS.

**Comment by amitaymolko** [comment]
What android version / device are you running on?
Please paste the full code that you are running as well.

**Comment by wesleyvandevoorde** [comment]
I have the same problem:
**TypeError: Cannot read property 'encrypt' of undefined**
Running with React-native: 0.53.2
RSA-native: 1.0.24
Android version: 9.0

`// @flow
import { RSA } from 'react-native-rsa-native';

export const encryptValue = (value: string, publicKey: string): Promise<string> =>
  new Promise(resolve => {
    RSA.encrypt(value, publicKey).then(encodedMessage => {
      resolve(encodedMessage.replace(/\s/g, ''));
    });
  });
`

**Comment by wesleyvandevoorde** [comment]
I also had to enable         
```multiDexEnabled true```
in my app/build.gradle

**Comment by MakhouT** [comment]
I am having the same issue as @wesleyvandevoorde and @NotTooReact89 
I am using a oneplus 5t with android version 8.1.0

**Comment by MakhouT** [comment]
Any progress on this @amitaymolko ?

**Comment by amitaymolko** [comment]
@MakhouT , @wesleyvandevoorde 
Can you make sure `RNRSAPackage` has been added in the `MainReactActivity.java ` or `MainApplication.java`:  
```
import com.RNRSA.RNRSAPackage;

mReactInstanceManager = ReactInstanceManager.builder()
.setApplication(getApplication())
...
...
 .addPackage(new MainReactPackage())
 .addPackage(new RNRSAPackage())
```  
or
```
 @Override
    protected List<ReactPackage> getPackages() {
      return Arrays.<ReactPackage>asList(
          new MainReactPackage(),
          new RNRSAPackage()
      );
    }
```

**Comment by wesleyvandevoorde** [comment]
@amitaymolko Thanks for the help! Addind this to mainapplication.java did the trick!
Also I had to add: 'multiDexEnabled true' in build.gradle
and 'org.gradle.jvmargs=-Xmx1536M' in my gradle.properties
but works on android now. Thanks!
