### ISSUE TITLE
Crash on iOS 9.3

### ISSUE THREAD

**Issue by jordenchang55** [amitaymolko/react-native-rsa-native#22]
After add this library, my app will crash on launch.
This happened only on iOS 9.3. Neither android nor iOS above 10.

Log in console:
```
dyld: Symbol not found: _kSecKeyAlgorithmRSAEncryptionPKCS1
Referenced from: ~/Library/Developer/CoreSimulator/Devices/8E4D3D08-FDD6-4A40-BA83-83BB05990B95/data/Containers/Bundle/Application/AFF781A8-19C7-465A-8716-6B0778B4D8E7/<MyApp>.app/<MyApp>
  Expected in: /Library/Developer/CoreSimulator/Profiles/Runtimes/iOS 9.3.simruntime/Contents/Resources/RuntimeRoot/System/Library/Frameworks/Security.framework/Security
 in ~/Library/Developer/CoreSimulator/Devices/8E4D3D08-FDD6-4A40-BA83-83BB05990B95/data/Containers/Bundle/Application/AFF781A8-19C7-465A-8716-6B0778B4D8E7/<MyApp>.app/<MyApp>
```

**Comment by crafterm** [comment]
Howdy, our deployment target within rsa-native is set to 10.3, I think thats the minimum supported iOS version due to the API's in use above - will let @amitaymolko confirm his thoughts about it.

**Comment by amitaymolko** [comment]
@jordenchang55 @crafterm 
Yes, unfortunately kSecKey libraries were only introduced in iOS 10: https://developer.apple.com/documentation/security/kseckeyalgorithmrsaencryptionpkcs1
So it should work iOS 10.0+

**Comment by nowlkaszick** [comment]
This should be added to the readme file as it is quite an important bit of information.

**Comment by amitaymolko** [comment]
@nowlkaszick 
You are correct.
Done
