### ISSUE TITLE
Error in documentation

### ISSUE THREAD

**Issue by DavoCg** [amitaymolko/react-native-rsa-native#27]
Hello,

Maybe I'm missing something but I think there is an error in the documentation

```
return RSAKeychain.encrypt(secret, keyTag) //should be RSAKeychain.encrypt(secret, keys.public)
      .then(encodedMessage => {
        console.log(encodedMessage);

        RSAKeychain.decrypt(encodedMessage, keyTag)
          .then(message => {
            console.log(message);
          })
        }) ```

**Comment by amitaymolko** [comment]
Hey @DavoCg 

`RSAKeychain.encrypt(secret, keys.public)` should also work.
We wanted to leave a way to encrypt based on the keytag, also its nice to have the encrypt/decrypt arguments similar.

**Comment by amitaymolko** [comment]
@DavoCg Actually it would work as:
`RSA.encrypt(secret, keys.public)` not `RSAKeychain.encrypt(secret, keys.public)`
Maybe we should add support for `RSAKeychain.encrypt(secret, keys.public)`

**Comment by DavoCg** [comment]
Hey yes I think it could be a good idea !

**Comment by amitaymolko** [comment]
I've changed my mind about this, if you want to encrypt with a public key use `RSA.encrypt(secret, keys.public)`.
`RSAKeychain.encrypt(secret, keyTag)` should stay as it is.
Please notice `RSAKeychain` is for using the keychain not the actual keys.
