### ISSUE TITLE
How to generate SHA256 key

### ISSUE THREAD

**Issue by ashishrokr** [amitaymolko/react-native-rsa-native#28]
How do i generate SHA256 key ? Appreciated your work,but if want to generate SHA256 then ?

IS there any method for that>?

**Comment by amitaymolko** [comment]
Can you please explain what you mean?  
If you are trying to encrypt/decrypt SHA512 then you'll need a different library, this lib is for RSA.

**Comment by ashishrokr** [comment]
Your generate method gives 2048 bits key,want to generate 256?

**Comment by amitaymolko** [comment]
That value is currently hardcoded.
You are welcome to submit a PR with this feature.

If I get the time I'll add this feature, I'm just not sure when I would have the time to get to it.

**Comment by ashishrokr** [comment]
Okk sure.

**Comment by TheBlusky** [comment]
I would love to see the feature.

I'm currently using your library, but I need 4096bits RSA Key. So for the moment, I'm using it to test other parts of my app, but if the feature is not developped when we need to release, I will have to drop `react-native-rsa-native` :-(

(I would like to build a PR for it, but I don't have the knowledge to properly implement it)

**Comment by amitaymolko** [comment]
This was released in v1.0.21
To keep backwards compatibility I've added a new function `RSA.generateKeys(4096)`
