### ISSUE TITLE
Generated Public is not vaild with opensll

### ISSUE THREAD

**Issue by fasibio** [amitaymolko/react-native-rsa-native#31]
Version: Android
I generated a Key Pair. 
If i use the Public Key and copy to a file. 
for Example: 
```
-----BEGIN RSA PUBLIC KEY-----\nMIIBCgKCAQEAop0q4PS1hfvGB07eMwXdHIKd+WAYbed6G6rus8zsRFRyBBS+TN0d\nI4hDfFeI4W0dZaP4GURqw3Ulc1TPepFN8XDU6CcuFbKuyBjMZNGuVWNl67xdLz0F\nJNZboZlvBaHkubEI7j3cXhXaENwyh4ljiZuFm5M71euke0jRpGJNs77mbWVvvlXY\nhMRxVzQFnfsf/rtzMmgtbdTR2qsMJOtCorKSkmdh06v61TGs5HYoY80AXlIedC8t\nIMBYPAwhHbaiu62m69llt+1aIxjIqy2EH4opevjTDPeDNTWDMrkoE++OPIetWokH\n6bdrWQZcEuVTUg26gf9Ns8Pgt6y9AE5FAQIDAQAB\n-----END RSA PUBLIC KEY-----\n
```
And check with openssl 
(I remove the String RSA
openssl rsa -noout -text -inform PEM -in pubKeyFile.pem -pubin
i get this error: 

```
unable to load Public Key
140585687942808:error:0D0680A8:asn1 encoding routines:ASN1_CHECK_TLEN:wrong tag:tasn_dec.c:1197:
140585687942808:error:0D07803A:asn1 encoding routines:ASN1_ITEM_EX_D2I:nested asn1 error:tasn_dec.c:374:Type=X509_ALGOR
140585687942808:error:0D08303A:asn1 encoding routines:ASN1_TEMPLATE_NOEXP_D2I:nested asn1 error:tasn_dec.c:697:Field=algor, Type=X509_PUBKEY
140585687942808:error:0906700D:PEM routines:PEM_ASN1_read_bio:ASN1 lib:pem_oth.c
```
What i do wrong. 
Why it is not Valid ? 
Thank you for help

**Comment by amitaymolko** [comment]
Hey,
The keys are formatted with RSA PUBLIC KEY and not PUBLIC KEY.
Great post explaining the formatting: https://stackoverflow.com/questions/18039401/how-can-i-transform-between-the-two-styles-of-public-key-format-one-begin-rsa/29707204#29707204
To import into openssl use `-RSAPublicKey_in` instead of `-pubin`:
`openssl rsa -in pubKeyFile.pem -text -noout -RSAPublicKey_in`

**Comment by fasibio** [comment]
thank you for fast feedback

**Comment by cgomezmendez** [comment]
Where you able to get a public key that can be used in openssl without converting?
