### ISSUE TITLE
Project documentation

### ISSUE THREAD

**Issue by amitaymolko** [amitaymolko/react-native-rsa-native#35]
The project needs some documentation explaining usage.

**Comment by jimcullenaus** [comment]
Is there any progress on this? Currently it is impossible to work out how to use this library because the examples in the README are very vague and don't explain what they are doing. And there is no other documentation available that I can find.

**Comment by amitaymolko** [comment]
No, sorry.
The examples do sum up the capabilities of the library.
They are pretty self-explanatory.
If you have any issues you can open an issue.

**Comment by jimcullenaus** [comment]
They're really not self-explanatory, I'm afraid.

What is the difference between `RSA.generateKeys()` and `RSA.generate()`? What does `RSAKeychain.generate()` do, and what is the role of the `keyTag`? Does all of it work on both Android and iOS?

What exactly does the act of chaining the `RSAKeychain.sign().then(...verify)` on to the result of the `RSAKeychain.encrypt().then(...decrypt)` do?

**Comment by amitaymolko** [comment]
`RSA.generateKeys()` lets you set the key size.
`RSA.generate()` is just short for `RSA.generateKeys(2048)`

`RSAKeychain` is very similar to `RSA` but it saves the private key in the device's keychain, iOS & Android support
https://developer.android.com/reference/android/security/KeyChain
https://developer.apple.com/documentation/security/keychain_services

The chaining is just js promises, `verify` uses the result from `sign` so it needs to wait for `verify`.
It should be written using async await, much cleaner

**Comment by jimcullenaus** [comment]
Okay, I will read up on those device keychains. I assume the purpose of `keyTag` is explained in those? Is it just an identifier so you can differentiate between multiple different keys stored on one device?

And are you saying that this would make storage of the keys automatic, so that the developer would not need to manage storage themselves?

Regarding the promise chaining, my question was more around why the result of the encrypt/decrypt promise gets chained on to the sign/verify one. Is that just a rushed example, or is there some connection between them? Specifically:

```
RSAKeychain.generate(keyTag)
.then(keys => {
  return RSAKeychain.encrypt(secret, keyTag)
  .then(encodedMessage => {
    RSAKeychain.decrypt(encodedMessage, keyTag)
    .then(message => {});
  });
}).then() => {
  // why is this part chained on to the result of the previous part?
  return RSAKeychain.sign(secret, keyTag)
  .then(signature => {
    RSAKeychain.verify(signature, secret, keyTag)
    .then(isValid => {
      // I assume isValid is a boolean?
    });
})
...
```

Cheers!

**Comment by amitaymolko** [comment]
`keyTag` is just an identifier.

Chaining: No real reason, just linking the examples on the same keyTag.
`isValid` should be a boolean

**Comment by jimcullenaus** [comment]
If it's alright with you, I might do a pull request later in the week to clarify some of this documentation.

Not sure precisely when it'll be, as I'm away from my main workstation for the next few weeks.

**Comment by amitaymolko** [comment]
That would be great!
Thanks!

**Comment by jimcullenaus** [comment]
Hey, PR has been created now.
