### ISSUE TITLE
Undefined using Expo

### ISSUE THREAD

**Issue by somentelucas** [amitaymolko/react-native-rsa-native#37]
Hi, I have an application running with Expo and I can't import `RSA`. Here is what I have:
```
import { RSA } from 'react-native-rsa-native'
console.log('RSA', RSA)
```

My log says it is `undefined`. Any idea why? Was it supposed to work with Expo? Thanks!

**Comment by amitaymolko** [comment]
Hey,
React Native Modules don't work with Expo.
Sorry.
