### ISSUE TITLE
it dose not support the privatekey encrypt ,publickey decrypt?

### ISSUE THREAD

**Issue by chenyao6134** [amitaymolko/react-native-rsa-native#38]
just as the title show ,it does not support this function

**Comment by amitaymolko** [comment]
You have the `sign` and `verify` methods.

**Comment by anagar23** [comment]
@amitaymolko , How will this work when server encrypt with private key and sends public key to client ?

**Comment by amitaymolko** [comment]
client can use public key with `verify` function to verify encrypted data

**Comment by anagar23** [comment]
@amitaymolko , but it also need signature and in my case I want to decrypt that data to use further.

**Comment by amitaymolko** [comment]
Whats the use case?
If you are decrypting sensitive data with a Public key it's not secure because anyone can have access to the Pulic key.

**Comment by anagar23** [comment]
I will store the public key into the keychain, so its not accessible for unauthorised user.

**Comment by amitaymolko** [comment]
Do you generate a key pair on the server for every user? Or is it only one for all users?

**Comment by anagar23** [comment]
@amitaymolko, Thanks for the help !

But now we are changing the flow with the standard one (public - encrypt, private - decrypt).
