### ISSUE TITLE
manual installation

### ISSUE THREAD

**Issue by aaronbuchanan** [amitaymolko/react-native-rsa-native#4]
I'd like to try this library out with our app, but we're not using cocoapods. Are there notes anywhere on how to manually link things up? Any other dependencies I need to also link? 

Thanks!

**Comment by crafterm** [comment]
@aaronbuchanan agreed - I think this will change shortly mate, with the removal of the OpenSSL dependency and use of the Apple Security code in #2. Locally I've created a xcodeproj with the .m/.h files that I bring into the react native project, much like react native itself, with no cocoapod dependencies. Will sing out when its available and perhaps you can give it a test for us?

**Comment by amitaymolko** [comment]
This has been fixed with PR #5
