### ISSUE TITLE
Cannot read property 'generateKeys' of undefined

### ISSUE THREAD

**Issue by faisalbasha1982** [amitaymolko/react-native-rsa-native#43]
Hi,

I am trying to implement RSA in react native ver 0.55.4 on IOS 11.4, I am getting the error as:

TypeError: Cannot read property 'generateKeys' of undefined
TypeError: Cannot read property 'encrypt' of undefined

I am not able to resolve this issue as I have saved the react-native-rsa-native via npm and imported
RSA, RSAKeychain?

**Comment by bachlongkocanh** [comment]
same error

**Comment by kodzonko** [comment]
generating keys and encryption/decryption **seem** to work for me in React Native environment but fail when I run these functions in jest unit tests:
```js
import { RSA } from "react-native-rsa-native";

const encrypted = await RSA.encrypt("test", <RSA public key I generated on device>);
const decrypted = await RSA.decrypt(encrypted, <RSA private key I generated on device>);
```

example error:
> Cannot read properties of undefined (reading 'encrypt')

How do I  test code that involves `react-native-rsa-native`? Is it even possible or do I need to patch these functions to run on a computer?
