### ISSUE TITLE
Export Compliance

### ISSUE THREAD

**Issue by qispark** [amitaymolko/react-native-rsa-native#46]
I'm just wondering if anyone has published an app on the App Store using this library.

For export compliance (https://help.apple.com/app-store-connect/#/devc3f64248f), one of the points says that if "Your app uses encryption limited to that within the Apple operating system" will not require further documentation.

Does this library fall under that category?

**Comment by sbayd** [comment]
Hey,

I am facing with the same problem. Any update on this?

**Comment by amitaymolko** [comment]
Yes it only uses Apple's built-in security apis
