### ISSUE TITLE
Encryption using .pem file which contains public key same as SwiftyRSA library

### ISSUE THREAD

**Issue by kirtishjain9** [amitaymolko/react-native-rsa-native#48]
Hi amitaymolko,

Thanks for your library.

I need to apply encryption on user password using .pem file which contains public key.
It should be working like SwiftyRSA library written for Swift coding language.

Could you please suggest me how to achieve this kind of encryption using your library in ReactNative which should work for both platforms (iOS/Android)? 

Thanks in advance

Best reagrds
Kirtish Jain

**Comment by amitaymolko** [comment]
I'm not sure what you are having trouble with.
Checkout the example.

Please post the code you are trying and are having issues with.

**Comment by kirtishjain9** [comment]
I've checked out your example but couldn't get any idea how to get public key which stored in .pem file and that .pem file is in my project folder itself. 

I couldn't code it bcoz I don't know how to pass .pem file to get public key from it.

Could you please get me through this by giving any idea?

Thanks & regards
Kirtish Jain

**Comment by amitaymolko** [comment]
you should use https://www.npmjs.com/package/react-native-fs to load the file into a string and then use the library regularly.
Closing, for now, reopen if you add code samples where its not working
