### ISSUE TITLE
pod file for react-native 6

### ISSUE THREAD

**Issue by billtlee** [amitaymolko/react-native-rsa-native#55]
Hi,

I have upgraded to react-native 6 and would like to use this package.  However, I don't know how to install this without cocoapods.  Will you guys be adding a pod file to the dist?

Thanks

**Comment by amitaymolko** [comment]
It's been added and it working from v1.0.26
https://github.com/amitaymolko/react-native-rsa-native/pull/56
https://github.com/amitaymolko/react-native-rsa-native/pull/57
