### ISSUE TITLE
'React/RCTBridgeModule.h' file not found

### ISSUE THREAD

**Issue by sajadabbasiu** [amitaymolko/react-native-rsa-native#58]
hello,
I get this error in xcode :
```
'React/RCTBridgeModule.h' file not found
```

**Comment by amitaymolko** [comment]
Did you run `react-native link react-native-rsa-native` ?

**Comment by richeterre** [comment]
I had the same issue despite linking the project. After a few tries (try cleaning your build folder in Xcode) it suddenly worked, however.

**Comment by j0n4th4n-1410** [comment]
I had the same issue, any suggestion?, I tried few times clean build folder and not work for me.

**Comment by amitaymolko** [comment]
Don't forget to run `pod update`
Also we just released v2.0.0 give it a try
