### ISSUE TITLE
not working on android

### ISSUE THREAD

**Issue by yoginair** [amitaymolko/react-native-rsa-native#61]

**Comment by yoginair** [comment]
ReactNativeJS: Possible Unhandled Promise Rejection (id: 2):
    Error: -----END RSA PRIVATE KEY not found

**Comment by amitaymolko** [comment]
Can you please paste your code

**Comment by SergeyMelnyk** [comment]
https://github.com/amitaymolko/react-native-rsa-native/issues/62#issuecomment-535905277

**Comment by Dror-Bar** [comment]
I'm having the same issue
Edit: what finally worked for me [here](https://github.com/amitaymolko/react-native-rsa-native/issues/62#issuecomment-1141884771)
