### ISSUE TITLE
Not running on Android, while using RSA.encrypt(msg,publicKey) method.

### ISSUE THREAD

**Issue by mayursarode4** [amitaymolko/react-native-rsa-native#62]
Getting error as:

> Error: Attempt to invoke virtual method 'byte[] org.spongycastle.asn1.x509.SubjectPublicKeyInfo.getEncoded()' on a null object reference
>     at createErrorFromErrorData (NativeModules.js:152)
>     at NativeModules.js:104
>     at MessageQueue.__invokeCallback (MessageQueue.js:442)
>     at MessageQueue.js:127
>     at MessageQueue.__guard (MessageQueue.js:343)
>     at MessageQueue.invokeCallbackAndReturnFlushedQueue (MessageQueue.js:126)
>     at debuggerWorker.js:80

 **While using RSA.enrypt(msg, publicKey) method.**

My code:
>const publicKey = keys.public; (I'm receiving from an API as RSA string response)
 >RSA.encrypt(paramText, publicKey)
   >         .then(encodedMessage => {
     >           console.log(`the encoded message is ${encodedMessage}`);
>}

Please reply soon.
Thank you.

**Comment by SergeyMelnyk** [comment]
you need use key like this 
-----BEGIN RSA PUBLIC KEY------**/r/n**YOUR_KEY**/r/n**-----END RSA PUBLIC KEY-----

**Comment by Dror-Bar** [comment]
@SergeyMelnyk Your suggestion didn't solve the issue...

Edit: Finally, I made a change that fixed it in my case. Maybe it will work for you as well.
I edited the file RSA.java inside node modules. This is the patch-package file for reference:

```
diff --git a/node_modules/react-native-rsa-native/android/src/main/java/com/RNRSA/RSA.java b/node_modules/react-native-rsa-native/android/src/main/java/com/RNRSA/RSA.java
index 7079d28..50ecba1 100644
--- a/node_modules/react-native-rsa-native/android/src/main/java/com/RNRSA/RSA.java
+++ b/node_modules/react-native-rsa-native/android/src/main/java/com/RNRSA/RSA.java
@@ -235,17 +235,17 @@ public class RSA {
     }
 
     private PublicKey pkcs1ToPublicKey(String publicKey) throws IOException, NoSuchAlgorithmException, InvalidKeySpecException {
-        Reader keyReader = null;
+        // Reader keyReader = null;
         try {
-            keyReader = new StringReader(publicKey);
-            PEMParser pemParser = new PEMParser(keyReader);
-            SubjectPublicKeyInfo subjectPublicKeyInfo = (SubjectPublicKeyInfo) pemParser.readObject();
-            X509EncodedKeySpec spec = new X509EncodedKeySpec(subjectPublicKeyInfo.getEncoded());
+            // keyReader = new StringReader(publicKey);
+            // PEMParser pemParser = new PEMParser(keyReader);
+            // SubjectPublicKeyInfo subjectPublicKeyInfo = (SubjectPublicKeyInfo) pemParser.readObject();
+            X509EncodedKeySpec spec = new X509EncodedKeySpec(Base64.decode(publicKey, Base64.DEFAULT));
             return KeyFactory.getInstance("RSA").generatePublic(spec);
                } finally {
-            if (keyReader != null) {
-                keyReader.close();
-            }
+            // if (keyReader != null) {
+            //     keyReader.close();
+            // }
         }
     }
```

After this change, it finally read and encrypted my custom public key. Do note that with this change I had the remove the
`-----BEGIN PUBLIC KEY----- ` and ` -----END PUBLIC KEY-----` from the key for it to work (in Android).
