### ISSUE TITLE
Cannot read property 'verify' of undefined in Jest

### ISSUE THREAD

**Issue by jianzuguan** [amitaymolko/react-native-rsa-native#63]
How I impletement:
`import { RSAKeychain } from 'react-native-rsa-native';`
`RSAKeychain.verify(signatureString, data, rsaPublicKey);`

Error I got in Jest unit test:
`TypeError: Cannot read property 'verify' of undefined`

Does anyone know how to solve this?

Or it is not possible to run in Jest as all the code sit in Android and iOS?

**Comment by amitaymolko** [comment]
I don't have experience with testing react native modules with jest but because the underlying library code is native it makes sense that jest wouldn't be able to run it.
