### ISSUE TITLE
How encrypt from publickey string

### ISSUE THREAD

**Issue by thanhtuyenpkk** [amitaymolko/react-native-rsa-native#64]
Here is my code 
let pub = '30820122300D06092A864886F70D01010105000382010F003082010A0282010100AE14891B84B9D0799BA0ED4BC3F1A1789EE9D895DF10E2E2FCD0129D1671C094D4A69EA30893F8798A5C1DF9E4F7A43F19E00812819C48B1BF75432770A08D5A6C47F9C4889C16AC128CE1CCF5E8C51BB46371867D1C22B0C1E3BF364F35305D5648BC99890441D5EFC2904128F8646742BD35E031040EA528F972F31C5F6D774FF4049ECFE9120DAEA96F60EAE20ABD662B56CB18FD04259BE63F907BA3C1EF93E773EA54D6E80773331055DCC007E79A9FD2FCEEE165CE5E8D6BB574BD65A09B2AA18A6A07A884355126B3C054AE6B6183C486F7C64E896421CAFDA30566A9F7FD264C383903BB1BB9C3ABE656EC92513210C87D61F285419144AEDC9E4F730203010001'
let message = "my secret message";
let ecrpyt = await  RSA.encrypt(message, pub);
I'm can't use this to encrypt. 
Is there any way to encrypt it?
Please help !!!

**Comment by thanhtuyenpkk** [comment]
const ArrBuffer = await utils.convertHexToArrayBuffer(pub);
console.log('ArrayBuffer', ArrBuffer)
const pubBase64 = await utils.convertArrayBufferToBase64(ArrBuffer);
const pubBase64 = base64.encode(pub);
console.log('pubBase64', pubBase64)
     
const length = pubBase64.length;
let newString = '-----BEGIN RSA PUBLIC KEY-----\n'
for (let index = 0; index < length; index = index + 64) {
      let last = index + 64;
      if (last < length) {
             newString += pubBase64.slice(index, last) + '\n';
      } else {
            newString += pubBase64.slice(index, length);
     }
 }

 newString += '\n-----END RSA PUBLIC KEY-----';

const rsaPub1 = await RSA.encrypt(message, newString);

I'm convert to base 64 but it not work?
.....................

**Comment by amitaymolko** [comment]
Hello, sorry for the late response.
It looks like you are formatting the key properly.
Can you print the public key here?

Here is a valid public key:
```
-----BEGIN RSA PUBLIC KEY-----
MIICCgKCAgEAr32KGY60KOzfdNHUl/HWVuSOo6PKxd8zOuvtfbq9T3TPJkYPOxBU
8PgC68SHPAuAXtlyWPYgKkTScDuvEHh6xao5c/nJdIanzQvVXTLhZyNVCgMRwlEi
konW4mQsQeaUSTor69cTZT3y3Uxv6l4RhcsMuHg5Upm6mTL4jsnqTqSx0bAq5Ysi
vSKcRfjfFh0jD6ENbXgRD5spgKwhV+l0ClYWKBnmbljTqFW8TRZkDo5qvpiAs96t
cyHLkkZxoXiG2s5+H89ANNPNvv12Fa1s2lcQLpY3Uouh/8ag0yxMQFnZivF5hAoU
LsngGn9UY81n61neldEeicgpHq4mHWObg36gZKjUPXM8hJNMxl/IIGg8DA8WGoea
nQgx1AvTnaIlWTcqX5b4O1wZCPS72qCwv/55fdvMXmpCyeNzynEm/JuLtoLtXnBe
vZMrT7AdidmmjauF4dPTW+3MXLSHbcy6284/6RKZJb7pw8RvDnVfeulmJvMYW4Ad
6R/QrHrIYcA9tfcP8JdQfz+Wppv0aEk9rJqq96J5H6zculaCWfEkD0F7KNFxzcS6
z1T8y10mgCxkY9b6z/sX/K7XJ9bDEdk8+GelCwygJrqKrAbqw/4w/OM4ceu/oSq1
HKkn6WPBke1P3jo8+51HejgU/SzNXV6QIfHI9dAZY19I2yFYT0AXItcCAwEAAQ==
-----END RSA PUBLIC KEY-----
```
