### ISSUE TITLE
Pod Install issue

### ISSUE THREAD

**Issue by camharless** [amitaymolko/react-native-rsa-native#71]
I am getting this when I attempt to run a pod install. Any idea why or what I can do to get this sorted out?

Thanks!

[!] CocoaPods could not find compatible versions for pod "react-native-rsa-native":
  In Podfile:
    react-native-rsa-native (from `../node_modules/react-native-rsa-native`)

Specs satisfying the `react-native-rsa-native (from `../node_modules/react-native-rsa-native`)` dependency were found, but they required a higher minimum deployment target.

**Comment by crafterm** [comment]
Sounds like your deployment target is less than 10 in the main app? Perhaps check that and see if it’s high enough?

**Comment by camharless** [comment]
I've changed it from 13.1 (where it was originally) to 13.2 and then some of the others to check that out in the info section of the project. Is there another way that I should test that I don't know about? I'm still very new to all of this.

**Comment by rBurgett** [comment]
I had this problem while trying to install for target 13.1. I had to force the `reac-native-rsa-native` to version 1.1.2 to get it working. Any version after that gives me the incompatible version error.

**Comment by IacoCesar** [comment]
same issue

**Comment by crafterm** [comment]
@camharless @rBurgett @IacoCesar thanks for the update everyone - can you please check your Podfile, and look for a line usually near the top that looks like:

platform :ios, 'x.x'

and make sure that is higher than 10? ideally it should match the deployment target you have in your Xcode project file.

I can reproduce the error you're describing with a sample app when that value is 9.0, which would be too low for react-native-rsa-native given the iOS API's we're using (10+).

Let me know how you get on?

**Comment by camharless** [comment]
It is at 9.0 in that file.

**Comment by ViniciusPaldes** [comment]
Thanks @crafterm ! 
I had the same problem my app was to IOS 9.0 +, I upgrade the number version on `project.pbxproj` to 10.0 but isn't enough.
After changing it on Podfile works fine, thanks!
