### ISSUE TITLE
React/RCTBridgeModule.h' file not found and not pod install execute

### ISSUE THREAD

**Issue by filiwoe** [amitaymolko/react-native-rsa-native#75]
when i compile for ios it gives me the following error

React/RCTBridgeModule.h' file not found

and there is also no error in the pod install

**Comment by matheussblima** [comment]
@filiwoe did you find any solution?

**Comment by vitorbarros** [comment]
+1

**Comment by AnoopN01** [comment]
In my case pod install was giving error CocoaPods could not find compatible versions for pod "react-native-rsa-native":
I had to change the ios version fro 9 to 11 in the pod file and the issue was resolved

**Comment by amitaymolko** [comment]
minimal pod ios version is 10.
Also we just released v2.0.0 give it a try
