### ISSUE TITLE
CocoaPods could not find compatible versions for pod "react-native-rsa-native"

### ISSUE THREAD

**Issue by GuilhermeTrivilin** [amitaymolko/react-native-rsa-native#79]
It is not the first time that I am having this error! I don't know what to do, it's the only project that has this error.

When running pod install, the terminal returns the following message:

```
[!] CocoaPods could not find compatible versions for pod "react-native-rsa-native":
  In Podfile:
    react-native-rsa-native (from `../node_modules/react-native-rsa-native`)

Specs satisfying the `react-native-rsa-native (from `../node_modules/react-native-rsa-native`)` dependency were found, but they required a higher minimum deployment target.
```

**Comment by amitaymolko** [comment]
min ios version needs to be 10.
https://github.com/amitaymolko/react-native-rsa-native/issues/71

**Comment by GuilhermeTrivilin** [comment]
Thanks, it works!

But for future developers who may have this error, it is necessary to update in two places!

In Xcode in the general tab and also at the top of the Podfile file.
