### ISSUE TITLE
My text encrypt fail 'error Error: -----END RSA PUBLIC KEY not found' => ANDROID

### ISSUE THREAD

**Issue by TruongNguyen95** [amitaymolko/react-native-rsa-native#93]
My friend send me key:

```
PUBLIC_KEY:
    '-----BEGIN RSA PUBLIC KEY-----MIGfMA0GCSqGSIb3DQEBAQUAA4GNADCBiQKBgQC' +
    'nvPQK6zV1EMameDMIwFIj61WQ7KD2vkCK1a+pnPgWsE/dgr6hR4Uory2U/peXcjm8gAfPQ' +
    'dNA93U65p2mc6VKf3YH7VfGUPFn/S6RYbcXsdeoz39rETAC5hDnOl+AIz2cxpKygxZBvLxzC' +
    'RinIT1ig0tDGguR5qI8zo9fC3MGgwIDAQAB-----END RSA PUBLIC KEY-----'
```
And my code:
```
import {RSA} from 'react-native-rsa-native';

export async function encryptString(txt: string) {
  let encryptTXT = await RSA.encrypt(txt, env.PUBLIC_KEY);
  return encryptTXT.replace(/(\r\n|\n|\r)/gm, '');
}
```
i had tried add `/r/n` or `\r\n` but it not work, please help

**Comment by Dror-Bar** [comment]
I have the same issue, is there any solution?
Adding `/n` introduced a new error `problem extracting key: java.lang.IllegalArgumentException: illegal object in getInstance: org.spongycastle.asn1.DLSequence`
Edit: what finally worked for me [here](https://github.com/amitaymolko/react-native-rsa-native/issues/62#issuecomment-1141884771)
