### ISSUE TITLE
Cannot read property 'generateKeys' of undefined

### ISSUE THREAD

**Issue by elmogof** [amitaymolko/react-native-rsa-native#94]
I'm trying to generate the keys but instead i'm recieving this message:
"Possible Unhandled Promise Rejection (id: 2):
TypeError: Cannot read property 'generateKeys' of undefined"

And this is the code:
import { RSA } from 'react-native-rsa-native';

{
     ...
     const keys = RSA.generateKeys(4096) //Problematic line
    ...
}

**Comment by VentroArt** [comment]
Update

**Comment by kriit24** [comment]
up

**Comment by BlockZap** [comment]
Up

**Comment by danramosd** [comment]
if you're running ios and using pods `$cd ios && pod install`

**Comment by rubytes** [comment]
up

**Comment by alessandrocapra** [comment]
How is this closed? I get the same (kinda, it's null and not undefined) as of today

**Comment by valqelyan** [comment]
Yeah same for me, it says `null`

`TypeError: Cannot read property 'generateKeys' of null`

**Comment by kommpn** [comment]
Error still present

**Comment by irfans18** [comment]
got same error here.

Additional Info : I'm using expo for react native development
